name: Linting

on: [pull_request]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm i

      - name: Run Lint
        run: npm run lint:prettier:check

  eslint:
    name: EsLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm i

      - name: Run Lint
        run: npm run lint:eslint:check

  commitLint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm i

      - name: Validate PR commits with CommitLint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
